# -*- coding: utf-8 -*-
"""Assignment2_student_sem1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sLYTsB7adZ59zQnTCne8LedbjIOksp2d

# Transfer Learning with Med MNIST.

In this assignment you will use transfer learning to train a model of your choice on a sub-dataset from the [MedMNIST datasets](https://medmnist.com/). ![](https://github.com/tonyscan6003/etivities/blob/main/medmnist.JPG?raw=true)

* The [MedMNIST package](https://github.com/MedMNIST/MedMNIST/blob/main/examples/getting_started.ipynb) allows the data to be imported directly as a pytorch dataset.

* You may select any of the datasets using Multi-class/binary classification. The goal is to acheve accuracy levels comparable to the benchmark results shown on the medmnist site. Dataloading for pytorch is setup in the notebook, you wil need to modify the code slightly depending on your dataset of choice.

* Some datasets use black and white images, so you will need to [at least concatenate](https://towardsdatascience.com/transfer-learning-on-greyscale-images-how-to-fine-tune-pretrained-models-on-black-and-white-9a5150755c7a) the input image channels (to 3 channels) for compatibility with the models pre-trained on imageNet.

* Some of the MedMNIST datasets don't contain too much data so Data augmentation may be essentila essential to avoid overfitting. In pytorch data augmentation is performed using the [transforms.v2](https://pytorch.org/vision/main/transforms.html) modules.

* In this notebook: You will need to import a model, and perform training. Tranfer Learning for computer vision is detailed [here](https://pytorch.org/tutorials/beginner/transfer_learning_tutorial.html)

* [Tensorboard can be imported](https://pytorch.org/tutorials/beginner/introyt/tensorboardyt_tutorial.html) to display results.

* Please only include one example of transfer learning in the submitted notebook. Making sure training curves/results are clearly visible. If you have trained additional transfer learning models (i.e. that were less successful) please add this as a table or report at the end of the notebook and/or in your final forum post.

# 1. Install & Import Packages
"""

!pip install medmnist
!pip install torchinfo

import torch
from torch import nn
from torchvision import datasets, models
from torchvision.transforms import ToTensor, v2, Pad, Grayscale
import matplotlib.pyplot as plt
from torch.utils.data import DataLoader
import numpy as np

"""## 2. Setup & Import Dataset
The [MedMNSIT](https://medmnist.com/) package (imported above) makes available several medical datasets available to access.

You can change the `data_flag` variable (dataset names are all lower case letters) to the dataset of your choice (Take care to note the parameters e.g. number of input channels below that will affect your model)


"""

import medmnist
from medmnist import INFO, Evaluator

for x in INFO:
    print(x)

data_flag = 'bloodmnist'
download = True

BATCH_SIZE = 64

info = INFO[data_flag]
task = info['task']
n_channels = info['n_channels']
n_classes = len(info['label'])

print('Type of Machine Learning Task = ',task)
print('Number of Input Data Channels = ',n_channels)
print('Number of Classes = ',n_classes)
print('The batch size for this dataset will be = ',BATCH_SIZE)

DataClass = getattr(medmnist, info['python_class'])

"""Transforms:
You can update the functions below with appropriate transforms for your particular use case.

* As well as being suitable for data augmention for image classification, the transforms.v2 package of torchvision extends transforms for object detection and segmentation tasks. An illustration of the transforms is shown [here](https://pytorch.org/vision/main/auto_examples/transforms/plot_transforms_illustrations.html#sphx-glr-auto-examples-transforms-plot-transforms-illustrations-py).
* Normalisation based on ImageNet parameters is included already. This should be used with all models pre-trained on ImageNet  




"""

# Added a normalization calculation (TODO: mention test data is not included snooping)
from torchvision import transforms

def get_mean_std_3d():
    tensor_transformer = v2.Compose([
        v2.ToDtype(torch.float32, scale=True),
        ToTensor()
    ])
    train_dataset = DataClass(split='train', transform=tensor_transformer, download=download, mmap_mode='r')
    train_dataloader = DataLoader(train_dataset, batch_size=len(train_dataset))
    for single_batch, _ in train_dataloader:
        c1 = single_batch[:,0,:,:]
        c2 = single_batch[:,1,:,:]
        c3 = single_batch[:,2,:,:]

        return ((
            c1.mean(),
            c2.mean(),
            c3.mean()), (

            c1.std(),
            c2.std(),
            c3.std()))

def get_mean_std_1d():
    tensor_transformer = v2.Compose([
        v2.ToDtype(torch.float32, scale=True),
        ToTensor()
    ])
    train_dataset = DataClass(split='train', transform=tensor_transformer, download=download, mmap_mode='r')
    train_dataloader = DataLoader(train_dataset, batch_size=len(train_dataset))
    for single_batch, _ in train_dataloader:
        return (
            single_batch.mean(),
            single_batch.std())

recalculate_normalization = True
if recalculate_normalization:
    print(get_mean_std_3d())
else:
    print("((tensor(0.7631), tensor(0.5381), tensor(0.5614)),")
    print(" (tensor(0.1366), tensor(0.1543), tensor(0.1692)))")

train_transforms = v2.Compose([
    ToTensor(),
    v2.ToDtype(torch.float32, scale=True),
    # organ a
    # v2.Normalize([0.4680], [0.2974]),
    # derma
    # v2.Normalize([0.7631, 0.5381, 0.5614], [0.1366, 0.1543, 0.1692]),
    # organ c
    # v2.Normalize([0.4942], [0.2834]),
    # v2.Grayscale(num_output_channels=3),
    # blood
    v2.Normalize([0.7943, 0.6597, 0.6962], [0.2156, 0.2416, 0.1179])
])

test_transforms = v2.Compose([
    ToTensor(),
    v2.ToDtype(torch.float32, scale=True),
    # organ a
    # v2.Normalize([0.4680], [0.2974]),
    # derma
    # v2.Normalize([0.7631, 0.5381, 0.5614], [0.1366, 0.1543, 0.1692]),
    # organ c
    # v2.Normalize([0.4942], [0.2834]),
    # v2.Grayscale(num_output_channels=3),
    # blood
    v2.Normalize([0.7943, 0.6597, 0.6962], [0.2156, 0.2416, 0.1179])
])

"""Setup your Medmnist dataset.
* The convolution part of pre-trained networks (such as resnet) are compatable with any size input image. However they were trained on 224 x 224 size images, with early layers finding small scale features and deeper layers finding large scale features.
* For this transfer learning application to medical data, the gap between the original ImageNet domain and the medical images is wide. Therefore the size/scale of the input images is less important, however in general we would expect better performance with the larger input images (as they contain more features at different scales).
* You can add the `size=224` parameter to the dataset object calls, to load full size images. Only do this once you are confident in your training methodology (or if the dataset is small), as training with full size images will take longer.

"""

# Download training data from open datasets.
# train_dataset = DataClass(split='train', transform=train_transforms, download=download, size=224, mmap_mode='r')
# test_dataset = DataClass(split='test', transform=test_transforms, download=download, size=224, mmap_mode='r')
# val_dataset = DataClass(split='val', transform=test_transforms, download=download, size=224, mmap_mode='r')

unaugmented_train_dataset = DataClass(split='train', transform=train_transforms, download=download, mmap_mode='r')
test_dataset = DataClass(split='test', transform=test_transforms, download=download, mmap_mode='r')
val_dataset = DataClass(split='val', transform=test_transforms, download=download, mmap_mode='r')

def sample_counts(data_set, name):
  display("")
  display(f"Sample counts for {name}")
  display({ f"{info['label'][str(int(i))]}": x for i, x in zip(*np.unique(data_set[:,0][1], return_counts=True)) })

sample_counts(unaugmented_train_dataset, "train")
sample_counts(val_dataset, "val")
sample_counts(test_dataset, "test")

from torch.utils.data import Dataset

class AugmentedDataset(Dataset):
    def __init__(self, unaugmented_dataset, transform):
        self.unaugmented_dataset = unaugmented_dataset
        self.transform = transform

    def __len__(self):
        return len(self.unaugmented_dataset) * 2
        # return len(self.unaugmented_dataset)

    def __getitem__(self, i):
      # return self.unaugmented_dataset[i]
      return self.unaugmented_dataset[i]\
        if i < len(self.unaugmented_dataset)\
        else self.transform(self.unaugmented_dataset[i - len(self.unaugmented_dataset)])

train_dataset = AugmentedDataset(unaugmented_train_dataset, v2.Compose([
    v2.RandomAdjustSharpness(2, 0.25),
    v2.RandomVerticalFlip(0.25),
    v2.RandomHorizontalFlip(0.25),
    v2.RandomRotation(degrees=25),
]))

"""The `Dataset` is passed as an argument to `DataLoader`. This wraps an
iterable over the dataset, and supports automatic batching, sampling,
shuffling and multiprocess data loading.
"""

# Create data loaders.
train_dataloader = DataLoader(dataset=train_dataset, batch_size=BATCH_SIZE, shuffle=True)
val_dataloader = DataLoader(dataset=val_dataset, batch_size=BATCH_SIZE, shuffle=False)
test_dataloader = DataLoader(dataset=test_dataset, batch_size=BATCH_SIZE, shuffle=False)

for X, y in test_dataloader:
    print(f"Shape of X [N, C, H, W]: {X.shape}")
    print(f"Shape of y: {y.shape} {y.dtype}")
    break

"""Plot some example augmented images"""

# Output next batch from dataloader
dataiter = iter(train_dataloader)
image_batch, labels_batch = next(dataiter)

# Use matplotlib to plot a sample of images

i=0
n_plots = 12 # number of plots
f, axarr = plt.subplots(1,n_plots,figsize=(20,10))

for image in image_batch[0:n_plots,:,:,:]:
  disp_image =  torch.permute(image,(2,1,0)).numpy() # return image to cpu for display and permute to channels last
  mean = np.array([0.7631, 0.5381, 0.5614])
  std = np.array([0.1366, 0.1543, 0.1692])
  disp_image = std * disp_image + mean
  disp_image = np.clip(disp_image, 0, 1)
  axarr[i].imshow(disp_image[:,:,:])
  axarr[i].axis("off")
  axarr[i].set_title(labels_batch[i].numpy(),fontsize='small')
  i = i+1

"""# 3. Define Transfer Learning model
Pytorch has an inbuilt [models package](https://pytorch.org/vision/stable/models.html) that allows loading of popular models with pre-trained weights.

* We want to add an additional classifier stage (to the output of the network). How to setup the [model is detailed here](https://discuss.pytorch.org/t/load-only-a-part-of-the-network-with-pretrained-weights/88397/2).
* This additional classifier may just be a single layer or a cascade of fully connected layers with dropout.
* Note that the number of parameters in the convolutional part of the model will be same no what the input size is set to. However the output feature map size will vary with input image size (small for small image, large for large image). This means the number of parameters in the additional classifier will change depending on input image size.

"""

# Get cpu, gpu or mps device for training.
device = (
    "cuda"
    if torch.cuda.is_available()
    else "mps"
    if torch.backends.mps.is_available()
    else "cpu"
)
print(f"Using {device} device")

from torchvision import models
from torchinfo import summary

def set_requires_grad(layer, value):
    """Sets the requires_grad property and returns the layer"""
    layer.requires_grad = value
    return layer

def remove_classifier_and_fix_weights(classifier_layer_name):

    def execute(layers):
        """
        Build a new nn.Sequential which has no classifier
            and where all of the weights are fixed.
            Modifies layers in place
        layers: nn.Sequential
        """

        return nn.Sequential(*[execute(layer) if isinstance(layer, nn.Sequential)
            else set_requires_grad(layer, False)
            for name, layer in layers.named_children() if name != classifier_layer_name])


    return execute

remove_classifier_and_fix_weights_alexnet = remove_classifier_and_fix_weights("classifier")
def classifier_alexnet(n_classes):
    return nn.Sequential(
        nn.Flatten(),
        nn.Dropout(p=0.5, inplace=False),
        nn.Linear(in_features=9216, out_features=4096, bias=True),
        nn.ReLU(inplace=True),
        nn.Dropout(p=0.5, inplace=False),
        nn.Linear(in_features=4096, out_features=4096, bias=True),
        nn.ReLU(inplace=True),
        nn.Linear(in_features=4096, out_features=n_classes, bias=True)
    )

remove_classifier_and_fix_weights_resnet18 = remove_classifier_and_fix_weights("fc")
def classifier_resnet18(n_classes):
    return nn.Sequential(
        nn.Flatten(),
        nn.Dropout(p=0.4, inplace=False),
        nn.Linear(in_features=512, out_features=n_classes, bias=True))

class TransferNet(nn.Module):
    def __init__(self, pretrained, n_classes):
        super(TransferNet, self).__init__()

        children = remove_classifier_and_fix_weights_resnet18(pretrained)

        self.layers = nn.Sequential(
            # take the classification and AvgPooling layers, drop the classification
            children,

            # create new classification head with same size network
            # as original AlexNet. (with different output param size)
            classifier_resnet18(n_classes))

    def forward(self, x):
        return self.layers(x)


#print(models.alexnet(weights=models.AlexNet_Weights.DEFAULT))
model = TransferNet(pretrained=models.resnet18(weights=models.ResNet18_Weights.IMAGENET1K_V1), n_classes=10)
print(model)
print(summary(model, depth=4))

"""# 4. Optimisation & Training Loop

Define a training loop that prints the loss from the training and validation set at least every epoch.
* You may choose to make the validation loss calculations more frequent so you can ensure training is progressing satisfactorily (especially with larger datasets).

* You can use tensorboard to visualise the [loss curves](https://pytorch.org/docs/stable/tensorboard.html))

* For multi-class classification classification problem we will use the  [CrossEntropy loss](https://pytorch.org/docs/stable/generated/torch.nn.CrossEntropyLoss.html). In this pytorch function, the input is the un-normalised logit value.

* You may  have to use [torch.squeeze](https://pytorch.org/docs/stable/generated/torch.squeeze.html) to reduce the dimensionality of the label tensor before passing it to the loss function (this due to how the dataset is configured and the loss will only accept 0D or 1D inputs)
"""

import torchvision
from torch.optim.lr_scheduler import OneCycleLR

def compile_blocks(block_type, layer):
    """
    Recursively grab any nn.Models out of a model in a
    depth first search
    """
    if isinstance(layer, block_type):
        yield layer
    else:
        for child in layer.children():
            for x in compile_blocks(block_type, child):
                yield x

def recursively_set_requires_grad(layer, value):
    """
    Recursively set required_grad on all nn.Modules
    """
    layer.requires_grad = value
    for child in  layer.children():
        recursively_set_requires_grad(child, value)

def build_required_grad_thunk(layer):
    """
    Build a thunk which will recursively set required_grad = True
    on all nn.Modules
    """
    def execute():
        recursively_set_requires_grad(layer, True)

    return execute

def evaluate_loss_values(loss_values, depth):
    pivot = len(loss_values) // 2
    first_half = sum(loss_values[0:pivot]) / pivot
    second_half = sum(loss_values[pivot:]) / (len(loss_values) - pivot)

    #todo document this + full class
    if first_half / second_half >= 1.005:
        return False

    if depth <= 1 or len(loss_values) < 10:
        return True

    return evaluate_loss_values(loss_values[pivot:], depth - 1)

class Scheduler():
    """
    A custom scheduler which incrementally unfreezes layers
    when the loss value is not improving
    """
    def __init__(self, model, optimizer, requires_grad_type, batch_average_count, n_epochs, steps_per_epoch):
        """
        model:
            the model to update
        requires_grad_type:
            A type which is a subclass of nn.Module
            The scheduler will work backwards through modules
            of this type setting requires_grad = True when the
            model is not learning
        batch_average_count:
            Number of batches to use when evaluating whether the
            model is learning or not
        """

        self.model = model
        self.loss_values = []
        self.requires_grad_layers = list(
            map(build_required_grad_thunk, compile_blocks(requires_grad_type, model))
        )
        self.unfreezable = len(self.requires_grad_layers)
        self.batch_average_count = batch_average_count

        self.lr_scheduler = OneCycleLR(
          optimizer,
          max_lr=0.01,
          steps_per_epoch=steps_per_epoch,
          epochs=n_epochs,
          anneal_strategy="linear",
          pct_start=0.4)

    def step(self, loss):
        """
        Execute scheduling
        loss:
            the latest loss value
        returns:
            True if the model was modified or a modification was
            not required
            False if a modification was required but all layers
            have already been updated
        """
        self.loss_values.append(loss)
        if len(self.loss_values) < self.batch_average_count:
            # print(len(self.loss_values) , self.batch_average_count)
            return True

        result = self.evaluate()
        # keep fixed size of loss values to evaluate
        if len(self.loss_values) > 0: self.loss_values.pop(0)
        return result

    def evaluate(self):
        pivot = len(self.loss_values) // 2
        first_half = sum(self.loss_values[0:pivot]) / pivot
        second_half = sum(self.loss_values[pivot:]) / (len(self.loss_values) - pivot)

        # print("f", first_half, "s", second_half, "t", first_half / second_half)

        #todo document this + full class
        if not evaluate_loss_values(self.loss_values, 2):
            return True

        result = self.set_next()

        # remove the first half of stats to give the
        # scheduler time to re-evaluate
        if result:
            self.loss_values = self.loss_values[pivot:]

        return result

    def set_next(self):
        if len(self.requires_grad_layers) == 0:
            return False

        print(f"Unfreezing layer {len(self.requires_grad_layers)} of {self.unfreezable}")
        set_requires_grad = self.requires_grad_layers.pop()
        set_requires_grad()
        return True

from torch.utils.tensorboard import SummaryWriter
from torch.utils.data import DataLoader
from torch import nn, optim
from datetime import datetime
import torchvision
import os

if not os.path.isdir("./best_results"):
    os.makedirs("./best_results")

def compile_stats(stats):
    """
    Build loss and accuracy stats from a list of batch results

    stats:
        [ (batch 1 size, batch 1 loss, batch 1 acc ratio),
          (batch 2 size, batch 2 loss, batch 2 acc ratio),
          ...
        ]
    """

    _, loss, results = zip(*stats)
    avg_loss = torch.as_tensor(loss).mean().item()
    avg_acc = torch.as_tensor(results).mean().item()

    return avg_loss, avg_acc

class Trainer():
    def __init__(self, model, data_train, data_val, device,
                 requires_grad_type,
                 batch_size=256,
                 lr=0.001,
                 weight_decay=0.0,
                 images_per_checkpoint=1_000,
                 n_epochs=20):
        """
        images_per_checkpoint:  the number of images to process before emitting
                                and event to the tensorboard writer
        """
        self.device = device
        self.model = model.to(device)
        self.images_per_checkpoint = images_per_checkpoint
        self.data_train = DataLoader(dataset=data_train, batch_size=batch_size, shuffle=True)
        self.data_val = DataLoader(dataset=data_val, batch_size=batch_size, shuffle=False)

        # def __init__(self, model, optimizer, requires_grad_type, batch_average_count, epochs, steps_per_epoch):
        self.optimizer = optim.Adam(self.model.parameters(), lr=lr, weight_decay=weight_decay)
        self.scheduler = Scheduler(self.model, self.optimizer, requires_grad_type,
                                   batch_average_count=10_000 // batch_size, n_epochs=n_epochs, steps_per_epoch=len(self.data_train))
        self.loss_fn = nn.CrossEntropyLoss()
        self.checkpoint = 0
        self.train_stats = []
        self.n_epochs = n_epochs

    def train(self):
        """
        Train the entire model
        """

        for e in range(1, self.n_epochs + 1):
            print(f"Starting epoch {e}")

            for batch_result in self.train_one_epoch():
                yield e, batch_result

    def train_one_epoch(self):
        """
        Train a single epoch
        """

        for data in self.data_train:
            batch_result = self.train_and_log_batch(data)
            if batch_result: yield batch_result

    def train_and_log_batch(self, batch):
        """
        Train a single batch and return a training set result
        if required (determined by images_per_checkpoint)
        """

        # odd case when batch just happens to be 1 image
        # the batch norm will fail
        if len(batch[0]) < 2:
          return None

        batch_result = self.train_batch(batch)
        count, _, _ = batch_result
        self.train_stats.append(batch_result)
        self.checkpoint += count

        return self.compile_and_reset_train_stats()\
            if self.checkpoint >= self.images_per_checkpoint\
            else None

    def compile_and_reset_train_stats(self):
        """
        Compile a training set result and reset totals to 0
        """

        stats = compile_stats(self.train_stats)
        ch = self.checkpoint

        self.train_stats = []
        self.checkpoint = 0

        return ch, stats

    def train_batch(self, batch):
        """
        Train on a batch, updating gradients and return results
        """

        loss, result = self.execute_batch(batch)
        loss.backward()
        self.optimizer.step()
        self.optimizer.zero_grad()
        self.scheduler.step(loss.item())

        return result

    def execute_batch(self, batch):
        """
        Execute a single batch and return results
        """

        inputs, labels = batch
        inputs, labels = inputs.to(self.device), labels[:,0].to(self.device)
        outputs = self.model(inputs)

        loss = self.loss_fn(outputs, labels)
        results = outputs.argmax(1) == labels
        return loss, (
            len(results),
            loss.item(),
            results.type(torch.float).mean().item())

    def validate(self):
        """
        Execute the entire validation data set and return loss and acc stats
        """

        self.model.train(False)
        try:
            stats = map(lambda x: self.execute_batch(x)[1], self.data_val)
            return compile_stats(stats)

        finally:
            self.model.train(True)

class LoggedTrainer():
    def __init__(self, name, trainer):
        """
        images_per_checkpoint:  the number of images to process before emitting
                                and event to the tensorboard writer
        """
        self.writer = None
        self.name = name
        self.trainer = trainer
        self.total_images = 0
        self.best_val_acc = 0

    def __enter__(self):
        self.writer = SummaryWriter(f'tensorboard/{round(datetime.now().timestamp())}')
        return self

    def __exit__(self, exception_type, exception_value, exception_traceback):
        self.writer.close()

    def train(self):
        """
        Train the entire model and emit results to tensorboard
        """

        for epoch, event in self.trainer.train():
            event_batch_size, (train_loss, train_acc) = event
            val_loss, val_acc = self.trainer.validate()
            self.write(epoch, event_batch_size, train_loss, train_acc, val_loss, val_acc)

            if val_acc > 0.7 and val_acc > self.best_val_acc + 0.001:
                print("Persisting model")
                torch.save(self.trainer.model.state_dict(), "./best_results/best.model")
                torch.save(self.trainer.model.state_dict(), f"./best_results/{val_acc}.model")
                self.best_val_acc = val_acc

    def write(self, epoch, event_batch_size, train_loss, train_acc, val_loss, val_acc):
        """
        Write test/validation stats to tensorboard
        """

        self.total_images += event_batch_size

        # TODO https://stackoverflow.com/questions/48951136/plot-multiple-graphs-in-one-plot-using-tensorboard
        print(f"Training Error, epoch {epoch}: \n Accuracy: {(train_acc*100):>0.1f}%, Avg loss: {train_loss:>8f}")
        print(f"Validation Error, epoch {epoch}: \n Accuracy: {(val_acc*100):>0.1f}%, Avg loss: {val_loss:>8f}\n")

        # Log the running loss averaged per batch
        self.writer.add_scalars('Loss',
                        { f'Training Loss {self.name}' : train_loss, f'Validation Loss {self.name}' : val_loss },
                        self.total_images)
        self.writer.add_scalars('Accuracy',
                        {f'Training Acc {self.name}' : train_acc, f'Validation Acc {self.name}' : val_acc },
                        self.total_images)

        self.writer.flush()

model = TransferNet(
    n_classes=len(info['label']),
    pretrained=models.resnet18(weights=models.ResNet18_Weights.DEFAULT))

with LoggedTrainer(
    name="x",
    trainer=Trainer(
        model=model,
        data_train=train_dataset,
        data_val=val_dataset,
        device=device,
        requires_grad_type=torchvision.models.resnet.BasicBlock,
        batch_size=256,
        lr=0.001,
        weight_decay=0.005,
        n_epochs=20,
        images_per_checkpoint=1_000)) as trainer:

    trainer.train()
#https://datascience.stackexchange.com/questions/47966/over-fitting-in-transfer-learning-with-small-dataset

! rm tensorboard.zip
! zip -r tensorboard.zip ./tensorboard/*

"""Initialise Tensorboard (use of tensorboard in colab notebooks is [detailed here](https://colab.research.google.com/github/tensorflow/tensorboard/blob/master/docs/tensorboard_in_notebooks.ipynb)). A [Pytorch tutorial](https://pytorch.org/tutorials/beginner/introyt/tensorboardyt_tutorial.html) shows how to setup the training and validation loop with pytorch.

"""

# Commented out IPython magic to ensure Python compatibility.
#%load_ext tensorboard
# %reload_ext tensorboard
# %tensorboard --logdir "tensorboard/1763914285" --bind_all

"""# 5. Evaluate Model
You will need to setup an evaluation loop for the model to assess it's performance on the test dataset.

You may also obtain a classification report after final evaluation of the test dataset with the model using the code below. A confusion matrix can also be obtained and we will plot a few example images.


"""

def best_model_from_cache():
    model = TransferNet(
        n_classes=len(info['label']),
        pretrained=models.resnet18()).to(device)
    model.load_state_dict(torch.load("./best_results/best.model"))
    model.train(False)
    return model

def execute_test():
    model = best_model_from_cache()
    data_test = DataLoader(dataset=DataClass(split='test', transform=test_transforms, download=download, mmap_mode='r'), batch_size=256)
    results = []
    for d in data_test:
        inputs, labels = d
        inputs, labels = inputs.to(device), labels[:,0].to(device)
        outputs = model(inputs)
        results.append((
            labels.detach().cpu().numpy(),
            outputs.argmax(1).detach().cpu().numpy(),
            outputs.detach().cpu().numpy()))

    y_true, y_pred, y_prob = zip(*results)
    return np.concatenate(y_true).ravel(), np.concatenate(y_pred).ravel(), np.concatenate(y_prob).ravel()

#https://scikit-learn.org/0.16/auto_examples/model_selection/plot_confusion_matrix.html
from sklearn.metrics import confusion_matrix

dataset_labels = list(info['label'].values())
y_true, y_pred, y_prob = execute_test()
print("Test accuracy", (y_true == y_pred).astype(float).mean())
cm = confusion_matrix(y_true, y_pred)
def plot_confusion_matrix(cm, title='Confusion matrix', cmap=plt.cm.Blues):
    trimmed_labels = list(map(lambda x: x if len(x) < 23 else (x[0:20] + "..."), dataset_labels))
    plt.imshow(cm, interpolation='nearest', cmap=cmap)
    plt.title(title)
    plt.colorbar()
    tick_marks = np.arange(len(info['label']))
    plt.xticks(tick_marks, trimmed_labels, rotation=70)
    plt.yticks(tick_marks, trimmed_labels)
    plt.tight_layout()
    plt.ylabel('True label')
    plt.xlabel('Predicted label')

plot_confusion_matrix(cm)

from sklearn.metrics import classification_report
print(classification_report(y_true, y_pred, target_names=dataset_labels))

""" # Comments about your Approach"""